
from PyQt6 import QtCore, QtGui, QtWidgets
import menuLogic
import player

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(532, 740)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(532, 740))
        MainWindow.setMaximumSize(QtCore.QSize(532, 740))
        font = QtGui.QFont()
        font.setPointSize(14)
        MainWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gameBoard = QtWidgets.QLabel(parent=self.centralwidget)
        self.gameBoard.setGeometry(QtCore.QRect(10, 0, 512, 512))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.gameBoard.sizePolicy().hasHeightForWidth())
        self.gameBoard.setSizePolicy(sizePolicy)
        self.gameBoard.setPixmap(QtGui.QPixmap("board.png"))
        self.gameBoard.setScaledContents(True)
        self.gameBoard.setObjectName("gameBoard")
        self.boardGrid = QtWidgets.QTableWidget(parent=self.centralwidget)
        self.boardGrid.setEnabled(True)
        self.boardGrid.setGeometry(QtCore.QRect(10, 0, 512, 512))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.boardGrid.sizePolicy().hasHeightForWidth())
        self.boardGrid.setSizePolicy(sizePolicy)
        self.boardGrid.setMinimumSize(QtCore.QSize(512, 512))
        self.boardGrid.setMaximumSize(QtCore.QSize(512, 512))
        self.boardGrid.setBaseSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(6)
        self.boardGrid.setFont(font)
        self.boardGrid.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.boardGrid.setAutoFillBackground(False)
        self.boardGrid.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.boardGrid.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.boardGrid.setFrameShadow(QtWidgets.QFrame.Shadow.Plain)
        self.boardGrid.setLineWidth(1)
        self.boardGrid.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.boardGrid.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.boardGrid.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.SizeAdjustPolicy.AdjustIgnored)
        self.boardGrid.setAutoScroll(False)
        self.boardGrid.setEditTriggers(QtWidgets.QAbstractItemView.EditTrigger.NoEditTriggers)
        self.boardGrid.setDragDropOverwriteMode(False)
        self.boardGrid.setAlternatingRowColors(False)
        self.boardGrid.setSelectionMode(QtWidgets.QAbstractItemView.SelectionMode.NoSelection)
        self.boardGrid.setShowGrid(False)
        self.boardGrid.setGridStyle(QtCore.Qt.PenStyle.DotLine)
        self.boardGrid.setWordWrap(True)
        self.boardGrid.setCornerButtonEnabled(False)
        self.boardGrid.setRowCount(16)
        self.boardGrid.setColumnCount(16)
        self.boardGrid.setObjectName("boardGrid")
        item = QtWidgets.QTableWidgetItem()
        self.boardGrid.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.boardGrid.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.boardGrid.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.boardGrid.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.boardGrid.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.boardGrid.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.boardGrid.setVerticalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.boardGrid.setVerticalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.boardGrid.setVerticalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.boardGrid.setVerticalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.boardGrid.setVerticalHeaderItem(10, item)
        item = QtWidgets.QTableWidgetItem()
        self.boardGrid.setVerticalHeaderItem(11, item)
        item = QtWidgets.QTableWidgetItem()
        self.boardGrid.setVerticalHeaderItem(12, item)
        item = QtWidgets.QTableWidgetItem()
        self.boardGrid.setVerticalHeaderItem(13, item)
        item = QtWidgets.QTableWidgetItem()
        self.boardGrid.setVerticalHeaderItem(14, item)
        item = QtWidgets.QTableWidgetItem()
        self.boardGrid.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.boardGrid.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.boardGrid.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.boardGrid.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.boardGrid.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.boardGrid.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.boardGrid.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.boardGrid.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.boardGrid.setHorizontalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.boardGrid.setHorizontalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.boardGrid.setHorizontalHeaderItem(10, item)
        item = QtWidgets.QTableWidgetItem()
        self.boardGrid.setHorizontalHeaderItem(11, item)
        item = QtWidgets.QTableWidgetItem()
        self.boardGrid.setHorizontalHeaderItem(12, item)
        item = QtWidgets.QTableWidgetItem()
        self.boardGrid.setHorizontalHeaderItem(13, item)
        item = QtWidgets.QTableWidgetItem()
        self.boardGrid.setHorizontalHeaderItem(14, item)
        self.boardGrid.horizontalHeader().setVisible(False)
        self.boardGrid.horizontalHeader().setCascadingSectionResizes(False)
        self.boardGrid.horizontalHeader().setDefaultSectionSize(32)
        self.boardGrid.horizontalHeader().setHighlightSections(False)
        self.boardGrid.horizontalHeader().setMaximumSectionSize(32)
        self.boardGrid.horizontalHeader().setSortIndicatorShown(False)
        self.boardGrid.horizontalHeader().setStretchLastSection(False)
        self.boardGrid.verticalHeader().setVisible(False)
        self.boardGrid.verticalHeader().setDefaultSectionSize(32)
        self.boardGrid.verticalHeader().setHighlightSections(True)
        self.boardGrid.verticalHeader().setMinimumSectionSize(0)
        self.playButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.playButton.setGeometry(QtCore.QRect(220, 610, 91, 51))
        self.playButton.setObjectName("playButton")
        self.topLabel = QtWidgets.QLabel(parent=self.centralwidget)
        self.topLabel.setGeometry(QtCore.QRect(80, 520, 371, 31))
        self.topLabel.setText("")
        self.topLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.topLabel.setObjectName("topLabel")
        self.logBox = QtWidgets.QTextEdit(parent=self.centralwidget)
        self.logBox.setEnabled(False)
        self.logBox.setGeometry(QtCore.QRect(10, 570, 1, 151))
        self.logBox.setAutoFillBackground(False)
        self.logBox.setFrameShadow(QtWidgets.QFrame.Shadow.Plain)
        self.logBox.setLineWidth(0)
        self.logBox.setReadOnly(True)
        self.logBox.setObjectName("logBox")
        self.rollButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.rollButton.setEnabled(False)
        self.rollButton.setGeometry(QtCore.QRect(324, 612, 161, 51))
        opEffect = QtWidgets.QGraphicsOpacityEffect()
        opEffect.setOpacity(0)
        self.rollButton.setGraphicsEffect(opEffect)
        self.rollButton.setObjectName("rollButton")
        self.inpTwo = QtWidgets.QPushButton(parent=self.centralwidget)
        self.inpTwo.setEnabled(False)
        self.inpTwo.setGeometry(QtCore.QRect(314, 580, 81, 31))
        opEffect = QtWidgets.QGraphicsOpacityEffect()
        opEffect.setOpacity(0)
        self.inpTwo.setGraphicsEffect(opEffect)
        self.inpTwo.setObjectName("inpTwo")
        self.horizontalLayoutWidget = QtWidgets.QWidget(parent=self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(329, 689, 151, 31))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pieceOneRadio = QtWidgets.QRadioButton(parent=self.horizontalLayoutWidget)
        self.pieceOneRadio.setEnabled(False)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.pieceOneRadio.setFont(font)
        self.pieceOneRadio.setStyleSheet("")
        self.pieceOneRadio.setObjectName("pieceOneRadio")
        self.horizontalLayout.addWidget(self.pieceOneRadio)
        self.pieceTwoRadio = QtWidgets.QRadioButton(parent=self.horizontalLayoutWidget)
        self.pieceTwoRadio.setEnabled(False)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.pieceTwoRadio.setFont(font)
        self.pieceTwoRadio.setObjectName("pieceTwoRadio")
        self.horizontalLayout.addWidget(self.pieceTwoRadio)
        self.pieceThreeRadio = QtWidgets.QRadioButton(parent=self.horizontalLayoutWidget)
        self.pieceThreeRadio.setEnabled(False)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.pieceThreeRadio.setFont(font)
        self.pieceThreeRadio.setObjectName("pieceThreeRadio")
        self.horizontalLayout.addWidget(self.pieceThreeRadio)
        self.pieceFourRadio = QtWidgets.QRadioButton(parent=self.horizontalLayoutWidget)
        self.pieceFourRadio.setEnabled(False)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.pieceFourRadio.setFont(font)
        self.pieceFourRadio.setObjectName("pieceFourRadio")
        self.horizontalLayout.addWidget(self.pieceFourRadio)
        self.endButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.endButton.setEnabled(False)
        self.endButton.setGeometry(QtCore.QRect(240, 710, 51, 23))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.endButton.setFont(font)
        opEffect = QtWidgets.QGraphicsOpacityEffect()
        opEffect.setOpacity(0)
        self.endButton.setGraphicsEffect(opEffect)
        self.endButton.setObjectName("endButton")
        self.inpFour = QtWidgets.QPushButton(parent=self.centralwidget)
        self.inpFour.setEnabled(False)
        self.inpFour.setGeometry(QtCore.QRect(314, 662, 81, 31))
        opEffect = QtWidgets.QGraphicsOpacityEffect()
        opEffect.setOpacity(0)
        self.inpFour.setGraphicsEffect(opEffect)
        self.inpFour.setObjectName("inpFour")
        self.inpThree = QtWidgets.QPushButton(parent=self.centralwidget)
        self.inpThree.setEnabled(False)
        self.inpThree.setGeometry(QtCore.QRect(130, 660, 81, 31))
        opEffect = QtWidgets.QGraphicsOpacityEffect()
        opEffect.setOpacity(0)
        self.inpThree.setGraphicsEffect(opEffect)
        self.inpThree.setObjectName("inpThree")
        self.inpOne = QtWidgets.QPushButton(parent=self.centralwidget)
        self.inpOne.setEnabled(False)
        self.inpOne.setGeometry(QtCore.QRect(130, 580, 81, 31))
        self.inpOne.setAutoFillBackground(False)
        opEffect = QtWidgets.QGraphicsOpacityEffect()
        opEffect.setOpacity(0)
        self.inpOne.setGraphicsEffect(opEffect)
        self.inpOne.setAutoDefault(False)
        self.inpOne.setDefault(False)
        self.inpOne.setFlat(False)
        self.inpOne.setObjectName("inpOne")
        self.logBox.raise_()
        self.gameBoard.raise_()
        self.boardGrid.raise_()
        self.playButton.raise_()
        self.topLabel.raise_()
        self.rollButton.raise_()
        self.inpTwo.raise_()
        self.horizontalLayoutWidget.raise_()
        self.endButton.raise_()
        MainWindow.setCentralWidget(self.centralwidget)

        #self.boardGrid.item()

        opEffect1 = QtWidgets.QGraphicsOpacityEffect()
        opEffect1.setOpacity(0)
        opEffect2 = QtWidgets.QGraphicsOpacityEffect()
        opEffect2.setOpacity(0)
        opEffect3 = QtWidgets.QGraphicsOpacityEffect()
        opEffect3.setOpacity(0)
        opEffect4 = QtWidgets.QGraphicsOpacityEffect()
        opEffect4.setOpacity(0)

        self.logBox.setGraphicsEffect(opEffect1)
        self.pieceOneRadio.setGraphicsEffect(opEffect1)
        self.pieceTwoRadio.setGraphicsEffect(opEffect2)
        self.pieceThreeRadio.setGraphicsEffect(opEffect3)
        self.pieceFourRadio.setGraphicsEffect(opEffect4)
        self.rollButton.setEnabled(False)

        logFont = QtGui.QFont()
        logFont.setPointSize(10)
        self.logBox.setFont(logFont)

        #self.boardGrid.editItem()
        #self.boardGrid.itemAt
        
        
        #onpress
        self.playPressed = 0
        self.playButton.pressed.connect(lambda: menuLogic.playButtPressed(self))

        self.inpOne.pressed.connect(lambda: menuLogic.playerAmountPressed(self, 1))
        self.inpTwo.pressed.connect(lambda: menuLogic.playerAmountPressed(self, 2))
        self.inpThree.pressed.connect(lambda: menuLogic.playerAmountPressed(self, 3))
        self.inpFour.pressed.connect(lambda: menuLogic.playerAmountPressed(self, 4))


        self.rollButton.pressed.connect(lambda: menuLogic.rollButt(self))

        self.endButton.pressed.connect(lambda: menuLogic.endGame(self))

        self.boardGrid.setWordWrap(True)
        #despite being given an exact size earlier, every column needs to be manually set to the correct width
        #why doesn't this effect rows? could it be that the cells are adjusting to nonexistant contents? WHO KNOWS
        for col in range(16):
                self.boardGrid.setColumnWidth(col, 32)
        #self.boardGrid.setItem(row,col, item)
        if False: #puts coords on each cell
                for row in range(16):
                        for col in range(16):
                                item = QtWidgets.QTableWidgetItem(str(row)+', '+str(col))
                                self.boardGrid.setItem(row,col, item)



        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Sorry!"))
        self.boardGrid.setSortingEnabled(False)
        item = self.boardGrid.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "0"))
        item = self.boardGrid.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "1"))
        item = self.boardGrid.verticalHeaderItem(2)
        item.setText(_translate("MainWindow", "2"))
        item = self.boardGrid.verticalHeaderItem(3)
        item.setText(_translate("MainWindow", "3"))
        item = self.boardGrid.verticalHeaderItem(4)
        item.setText(_translate("MainWindow", "4"))
        item = self.boardGrid.verticalHeaderItem(5)
        item.setText(_translate("MainWindow", "5"))
        item = self.boardGrid.verticalHeaderItem(6)
        item.setText(_translate("MainWindow", "6"))
        item = self.boardGrid.verticalHeaderItem(7)
        item.setText(_translate("MainWindow", "7"))
        item = self.boardGrid.verticalHeaderItem(8)
        item.setText(_translate("MainWindow", "8"))
        item = self.boardGrid.verticalHeaderItem(9)
        item.setText(_translate("MainWindow", "9"))
        item = self.boardGrid.verticalHeaderItem(10)
        item.setText(_translate("MainWindow", "10"))
        item = self.boardGrid.verticalHeaderItem(11)
        item.setText(_translate("MainWindow", "11"))
        item = self.boardGrid.verticalHeaderItem(12)
        item.setText(_translate("MainWindow", "12"))
        item = self.boardGrid.verticalHeaderItem(13)
        item.setText(_translate("MainWindow", "13"))
        item = self.boardGrid.verticalHeaderItem(14)
        item.setText(_translate("MainWindow", "15"))
        item = self.boardGrid.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "0"))
        item = self.boardGrid.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "1"))
        item = self.boardGrid.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "2"))
        item = self.boardGrid.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "3"))
        item = self.boardGrid.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "4"))
        item = self.boardGrid.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "5"))
        item = self.boardGrid.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "6"))
        item = self.boardGrid.horizontalHeaderItem(7)
        item.setText(_translate("MainWindow", "7"))
        item = self.boardGrid.horizontalHeaderItem(8)
        item.setText(_translate("MainWindow", "8"))
        item = self.boardGrid.horizontalHeaderItem(9)
        item.setText(_translate("MainWindow", "9"))
        item = self.boardGrid.horizontalHeaderItem(10)
        item.setText(_translate("MainWindow", "10"))
        item = self.boardGrid.horizontalHeaderItem(11)
        item.setText(_translate("MainWindow", "11"))
        item = self.boardGrid.horizontalHeaderItem(12)
        item.setText(_translate("MainWindow", "12"))
        item = self.boardGrid.horizontalHeaderItem(13)
        item.setText(_translate("MainWindow", "13"))
        item = self.boardGrid.horizontalHeaderItem(14)
        item.setText(_translate("MainWindow", "15"))
        self.playButton.setText(_translate("MainWindow", "Play!"))
        self.rollButton.setText(_translate("MainWindow", "ROLL"))
        self.inpTwo.setText(_translate("MainWindow", "2"))
        self.pieceOneRadio.setText(_translate("MainWindow", "1"))
        self.pieceTwoRadio.setText(_translate("MainWindow", "2"))
        self.pieceThreeRadio.setText(_translate("MainWindow", "3"))
        self.pieceFourRadio.setText(_translate("MainWindow", "4"))
        self.endButton.setText(_translate("MainWindow", "end"))
        self.inpFour.setText(_translate("MainWindow", "4"))
        self.inpThree.setText(_translate("MainWindow", "3"))
        self.inpOne.setText(_translate("MainWindow", "1"))
        
